feat(swizzling): REM-25021 Rewrite NSURLSessionTask swizzling
rakutentech/ios-perftracking pull request #24
Opened 2018-01-23 02:38 UTC by donnie-jp

- use IMP blocks for swizzling instead of the approach where new selector methods were created on categories so that selectors are unmodified
- remove unit tests that relied on the old selector IMP swapping approach
- remove NSURLSessionTask swizzling category because it is incompatible with the new approach
- use separate sessions for the delegate-based unit tests to improve test isolation

2018-01-23 07:16 UTC, vito1188 requested changes

2018-01-23 07:16 UTC, vito1188 commented on RPerformanceTracking/Private/_RPTClassManipulator+NSURLSessionTask.m
> +                    types:"@@:l"];
Does 'setState:' method return an object?

2018-01-23 09:42 UTC, donnie-jp commented on RPerformanceTracking/Private/_RPTClassManipulator+NSURLSessionTask.m
> +                    types:"@@:l"];
No, it's void. I've fixed it. Thanks

2018-01-24 01:03 UTC, vito1188 approved these changes
approve!

2018-01-24 01:27 UTC, merged