Enable battery monitoring
rakutentech/ios-perftracking pull request #5
Opened 2017-11-10 08:58 UTC by vito1188

2017-11-10 13:24 UTC, donnie-jp commented on RPerformanceTracking/Private/_RPTTrackingManager.m
> +        [UIDevice currentDevice].batteryMonitoringEnabled = YES;
I think we should enable battery monitoring at the end of the above while loop i.e. only enable monitoring if tracking is enabled. And we should disable monitoring if tracking gets turned off.

2017-11-10 13:24 UTC, donnie-jp requested changes
Inline comments

2017-11-14 04:56 UTC, vito1188 commented
update PR

2017-11-14 05:11 UTC, donnie-jp approved these changes

2017-11-14 05:12 UTC, merged